# Generated by Django 5.2.8 on 2025-12-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descriçao',
            new_name='descricao',
        ),
    ]
