# Generated by Django 6.0 on 2025-12-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.CharField(choices=[('I', 'Inativo'), ('A', 'Ativo')], default='A', max_length=1),
        ),
    ]
