# Generated by Django 6.0 on 2025-12-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produto_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
    ]
