# Generated by Django 6.0 on 2025-12-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_venda_status_alter_venda_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
