# Generated by Django 6.0 on 2025-12-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_venda_valor_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('E', 'Atrasado')], default='A', max_length=1)),
                ('tipo', models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber')], max_length=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendedor')),
            ],
        ),
    ]
