# Generated by Django 6.0 on 2026-01-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_caixa_mov_itemvenda_sub_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='caixa_mov',
        ),
    ]
