# Generated by Django 6.0 on 2026-01-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_caixa_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='tipo_venda',
            field=models.CharField(choices=[('O', 'Orcamento'), ('P', 'Pedido')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='tipo_mov',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida'), ('C', 'Custo')], max_length=1),
        ),
    ]
