# Generated by Django 6.0 on 2026-01-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_venda_tipo_venda_alter_movimento_tipo_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='just_cancelamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Faturado'), ('C', 'Cancelado')], default='A', max_length=1),
        ),
    ]
