# Generated by Django 6.0 on 2026-01-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_venda_just_cancelamento_alter_venda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.venda'),
        ),
    ]
