# Generated by Django 6.0 on 2026-01-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_itemvenda_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='cargo',
            field=models.CharField(choices=[('J', 'VendedorJ'), ('S', 'VendedorS'), ('R', 'Representante'), ('G', 'Gerente')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
