# Generated by Django 6.0 on 2026-02-07 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_vendedor_cargo_vendedor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('razao_social', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=90)),
                ('cnpjcpf', models.CharField(max_length=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpfcnpj',
            field=models.CharField(default=0, max_length=18),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'PreNota'), ('P', 'NotaProcessada')], max_length=1)),
                ('valor_nota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('razao_social', models.CharField(blank=True, max_length=90)),
                ('frete', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='ItensEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_item', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('quantidade_item', models.DecimalField(decimal_places=2, max_digits=8)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.entrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
        ),
    ]
