# Generated by Django 6.0 on 2026-02-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_fornecedor_cliente_cpfcnpj_entrada_itensentrada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro',
            old_name='valor',
            new_name='valor_parcela',
        ),
        migrations.AddField(
            model_name='financeiro',
            name='saldo_parcela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='tipo',
            field=models.CharField(choices=[('P', 'Pagar'), ('R', 'Receber'), ('C', 'Credito')], max_length=1),
        ),
    ]
