# Generated by Django 6.0 on 2026-02-25 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_valor_financeiro_valor_parcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='pago',
            field=models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('C', 'Parcial'), ('E', 'Atrasado')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Logfinancas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('B', 'Baixa'), ('R', 'Remocao Baixa'), ('D', 'Delete'), ('A', 'Alteraçao'), ('C', 'Criaçao')], max_length=1)),
                ('valor_acao', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('financeiro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.financeiro')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
