# Generated by Django 5.2.11 on 2026-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_financeiro_pago_logfinancas'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfinancas',
            name='id_financa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
