# Generated by Django 5.2.11 on 2026-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_logfinancas_id_financa'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfinancas',
            name='valor_saldo_parcela',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='logfinancas',
            name='acao',
            field=models.CharField(choices=[('BAIXAR', 'Baixa'), ('REM BAIXA', 'Remocao Baixa'), ('DELETE', 'Delete'), ('ALTER', 'Alteraçao'), ('CREATE', 'Criaçao')], max_length=12),
        ),
    ]
